### ISSUE TITLE
introduce concept of global config file

### ISSUE THREAD

**Issue by tsember** [tsember/freight-portal#10]
the name of the input directory (and anything else important to the entire system) should be read from a config file. The name of the config file is the first command line argument.

**Comment by jpsember** [comment]
I recommend making it a hidden json file in the user's home directory, e.g. ".freight-portal-defaults.json", and make that filename overridable via a pair of command line arguments, "-c", "<filename>"  (because it will quickly get out of hand if you assume the first cmd line argument is for this purpose).

**Comment by tsember** [comment]
this is implemented but the name is hard-coded. another issue will allow the name to be changed via command line arguments.
