### ISSUE TITLE
Emails we generate probably need to become a "store" like Shipments, Requests, etc

### ISSUE THREAD

**Issue by tsember** [tsember/freight-portal#137]
So far in the code whenever i know we will send a customer an email I have simply printed it in the log.

But they really are objects just like everything else. And that way we could test for their existence in the unit tests.

I haven't thought this through all the way, but it seems to me they could be thought of us discrete objects that are going out to various places. So just like the entry of a shipment in to the system generates Shipment and Request objects, it also generates Email objects to carriers and/or customers.

certainly email address,
probably subject which is maybe the same as shipment_id

would all be the relational fields we need to look up on. The unit test for the ShipmentDesk that checks carriers fixed-rate routes needs to answer the question:

did we send "customer 75" a message regarding "Shipment 534"?

it probably doesn't matter the content of the message at this point for testing, we know what it is about.

same thing, we need to know if we sent the Help Desk an email...

**Comment by jpsember** [comment]
Yes, let's make a protocol buffer (protobuf) message for emails.  I think a timestamp, sender, recipient(s), subject, body is sufficient.   The subject and body will be strings that will be generated by whatever code is sending the email... it doesn't need to store any customer or other ids, since we don't want the email tied to its particular use.
