### ISSUE TITLE
Shipment JSON file management

### ISSUE THREAD

**Issue by tsember** [tsember/freight-portal#22]
The Shipments make their way thru the freight-portal project as JSON files.

- [x] each Desk will have an input directory where it looks for these files.
- [x] each Desk will have an output directory where it puts the shipment file after operating on it.
- [x] each Desk will therefore delete the file from its input directory after reading it.
- [x] each Desk may decide it want to back up everything it operates on, in which case it will move the input file to a backup directory instead if just deleting it.
- [ ] a cleaner process will go thru a list of directories (which will be the set of backup directories) and remove any files that are "N" days old, so the disk doesn't fill up. **Probably not necessary**

**Comment by jpsember** [comment]
I suggest creating a 'backup' directory, and when you've successfully dealt with a shipment file, move it to the backup directory.  This is simpler, and safer, than copying and deleting it.

A nice way to do this is to specify a 'source' directory, which I think you've already got; the one that's crawled through to find json files.  Also specify a 'backup' directory, which is NOT a descendant of the source directory.  Then, when you want to move from the source to the backup, construct the backup File so it has the same path for elements following the source directory, i.e.,

If source directory is "~/work/alpha",
File being processed is "~/work/alpha/one/two/x.json",
and backup directory is "~/backup",
then the backup file is "~/backup/one/two/x.json".

You will need to do a 'mkdirs' for the directory(s) containing the backup file, since it won't automatically create them when you want to write new file. Try backupFile.getParentFile().mkdirs(), before moving the file from source to backupFile.
