### ISSUE TITLE
GitHub is saying that Jeff pushed commits when in fact Tim did them

### ISSUE THREAD

**Issue by jpsember** [tsember/freight-portal#64]
**This went away... maybe it's a bug on GitHub's end.**

It could be related to the computer having been mine a while back.

Or, some sort of global .gitconfig file is using my name instead of Tim's.

**Comment by jpsember** [comment]
In my home directory, I have this file:
```
cat ~/.gitconfig

[user]
  name = Jeff Sember
  email = jpsember@gmail.com

[core]
  excludesfile = /Users/home/.gitignore_global


[alias]
  # Do git unstage <file> to unstage files
  unstage = reset HEAD

  lg = log --pretty=format:\"%h (%an)    %s\" -60
  pl = 'pull --rebase'
  co = checkout
  st = status
  undo = checkout --

  # Type 'git newtask <branchname>' to start a new task
  newtask = checkout origin/master -b

[push]
  default = current


# To push ALL branches to remote, including any new ones,
# git push --all origin
[filter "lfs"]
  required = true
  clean = git-lfs clean %f
  smudge = git-lfs smudge %f
```

@tsember , what do you have for the 'user' section at the top of this file?

**Comment by tsember** [comment]
i have
[user]
 name = Tim Sember
 email = tim.sember@gmail.,com

and nothing else.

This error has been around ever since we started. I think the credentials i use to get in to github on this computer are yours, but it gets me in to "my" account. I have not spent any time on this since i got it all working, i will revisit it now that i have a chance at solving these problems.

From my point of view on this computer, it seems to think you did everything, but there are differences. The fact that my picture is a purple/white checkerboard really helps, because anything i do that appears, and if you do something, it is your picture. So that may be the key to the problem...

and this is why i haven't tried to solve, the picture solves it. But some other subtle change just happened a few days ago, i will try and figure out what it is... because i have not changed anything.

**Comment by tsember** [comment]
on Bruce's computer, who did what all looked correct between tsember and jpsember

**Comment by jpsember** [comment]
No big deal, closing...
