### ISSUE TITLE
Get 'cmit' working on Tim's computer

### ISSUE THREAD

**Issue by jpsember** [tsember/freight-portal#69]
See: https://github.com/jpsember/cmit

**Comment by tsember** [comment]
i downloaded this from Github and placed it in my .rbenv/shims directory.

but it doesn't work yet, environment path problems of other (i think ruby) stuff.

will revisit another time.

**Comment by jpsember** [comment]
You don't want to be messing with the `.rbenv` directory yourself.  

1. Remove whatever you put in there in your last comment
1. Clone the gem from github, by going to your Desktop directory and:
1. `git clone git@github.com:jpsember/cmit.git`
1. `cd cmit` (move into that directory)
1. `gem build cmit.gemspec`
1. `gem install cmit`
1. `rbenv rehash` (I don't know, more hacker nonsense)

**Comment by tsember** [comment]
cmit does not exist in my .rbenv/shims directory, but i know i put it there. and now the command line does not find cmit. so something is pretty disturbing, i had closed all my text shells, so whatever i had done proved temporary...

i think i need more of your enviroment, i cannot install cmit because:

cmit> gem install cmit
ERROR:  Could not find a valid gem 'js_base' (>= 1.0.1) in any repository
ERROR:  Possible alternatives: ais_base, aws-base, base, debase, jambase
